### ISSUE TITLE
Add extra colour options

### ISSUE THREAD

**Issue by OwainWilliams** [WildSiteCreations/Our.Community.MediaColourFinder#2]
### Feature summary

Average Colour from focal point
OPPOSITE COLOUR OF THIS AVERAGE
Light or Dark depending on average colour, so text can be white or black or something

**Comment by Bakersbakebread** [comment]
This was delivered in #3 ; 

But the issue should remain open to handle the refactoring of the logic around these extra colours, especially naming conventions to avoid confusions and make the properties reflective of their intent.
